# Generated by Django 5.1.2 on 2024-11-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitycomment',
            options={'verbose_name': 'Opportunity Comment', 'verbose_name_plural': 'Opportunities Comments'},
        ),
    ]
