# Generated by Django 5.1.2 on 2024-11-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_opportunitycomment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcomment',
            options={'verbose_name': 'Product Comment', 'verbose_name_plural': 'Products Comments'},
        ),
    ]
