# Generated by Django 5.1.2 on 2024-11-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_datapopulationlog_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubcategory',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
